config/routes.rb
Rails.application.routes.draw do
  get 'aquariu/show'
  get 'tauru/show'
  get 'scorpio/show'
  get 'arie/show'
  get 'gemini/show'
  get 'sagittariu/show'
  get 'characters/new'
  get 'characters/create'

  # INVENTORY
  get "/inventory", to: "inventory#index"
  put "/inventory", to: "inventory#update"

  resource :session
  resource :registration
  resource :password_reset
  resource :password
  resources :quests
  resources :items , only: [:index, :show, :new, :edit, :create, :update, :destroy] 
  resources :questions
  resources :npcs

  resource :game_master
  resources :rewards, only: [:index, :show]
  
  resources :characters
  resources :parties

  get '/game_map/:id', to: 'game_map#show', as: 'game_map'
  resources :arie
  resources :gemini
  resources :sagittariu
  resources :scorpio
  resources :tauru
  resources :aquariu

  
  # Defines the root path route ("/")
  root "main#index"
end

app/models/archer.rb
class Archer < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  # belongs_to :classe
  belongs_to :user

end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
    has_many :character
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/enigma.rb
class Enigma < ApplicationRecord
    validates :question, presence: true
    validates :correct_response, presence: true, inclusion: { in: %w(response1 response2 response3) }
    validates :response1, presence: true
    validates :response2, presence: true
    validates :response3, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates :path, presence: true
    validates :name, presence: true
    validates :categorie, presence: true
    validates :description, presence: true
    validates :stats, presence: true
end

app/models/mage.rb
class Mage < ApplicationRecord
end

app/models/npc.rb
class Npc < ApplicationRecord
    attr_accessor :avatar
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
end

app/models/quest.rb
class Quest < ApplicationRecord
    belongs_to :item_1, class_name: 'Item', foreign_key: 'item_1_id'
    belongs_to :item_2, class_name: 'Item', foreign_key: 'item_2_id'
    belongs_to :item_3, class_name: 'Item', foreign_key: 'item_3_id'
  end
  

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
    normalizes :email, with: ->(email) {email.strip.downcase}

    has_many :characters
    has_many :parties
end

app/models/warrior.rb
class Warrior < ApplicationRecord
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
before_action :set_quest, only: %i[show edit update destroy]
  
  def index
    @quests = Quest.all
    @items = Item.all
  end
  
  def show
    @quest = Quest.find(params[:id])
  end
  
  def new
    @quest = Quest.new
  end
  
  def create
    @quest = Quest.new(quest_params)
  
    if @quest.save
      redirect_to @quest
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @quest.update(quest_params)
      redirect_to @quest
    else
      render :edit
    end
  end

  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy
  end
  
  private
  
  def set_quest
    @quest = Quest.find(params[:id])
  end
  
  def quest_params
    params.require(:quest).permit(:name, :description, :exp, :item_1_id, :item_2_id, :item_3_id)
  end
end

app/helpers/arie_helper.rb
module ArieHelper
end

app/helpers/enigma_helper.rb
module EnigmaHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/tauru_helper.rb
module TauruHelper
end

app/views/quests/_form.html.erb
<div class="text-white text-center">
    <div class="flex items-center justify-center h-screen">
        <div class="absolute grid grid-rows-1 gap-8 place-content-center text-black">
        <%= form_with(model: @quest, local: true) do |form| %>
          <% if @quest.errors.any? %>
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
              <strong class="font-bold">Oops!</strong>
              <span class="block sm:inline"> <%= pluralize(@quest.errors.count, 'error') %> prohibited this quest from being saved:</span>
              <ul>
                <% @quest.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
       
          <div class="grid grid-rows-1 gap-4 mt-10 place-content-center">
            <div>
                <%= form.label :name, class: 'block text-black font-medium mb-2' %>
                <%= form.text_field :name, class: 'bg-transparent shadow appearance-none border rounded w-[20em] py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
            </div>
            <div>
                <%= form.label :exp, class: 'block text-black font-medium mb-2' %>
                <%= form.number_field :exp, class: 'bg-transparent shadow appearance-none border rounded w-[20em] py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
            </div>
            <div>
              <%= form.label :description, class: 'block text-blac font-medium mb-2' %>
              <%= form.text_area :description, class: 'bg-transparent shadow appearance-none border rounded w-[20em]  h-[6em] py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
            </div>
            <div class="w-25 grid gap-1 grid-rows-3">
              <%= form.collection_select :item_1_id, Item.all, :id, :name, prompt: 'Select item 1' %>
              <%= form.collection_select :item_2_id, Item.all, :id, :name, prompt: 'Select item 2' %>
              <%= form.collection_select :item_3_id, Item.all, :id, :name, prompt: 'Select item 3' %>
            </div>

            <div class="relative flex justify-center">
                <img src="/assets/home/button_home3.png" class="w-[200px] custom_link">
                <%= form.submit 'Save Quest', class: 'absolute top-[52px] text-white hover:text-[#E92306] custom_link' %>
            </div>
          </div>
        <% end %>
    </div>
</div>

app/views/quests/edit.html.erb
<!-- app/views/quests/edit.html.erb -->
<h1>Edit Quest</h1>

<%= render 'form' %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<div class="overflow-hidden text-white text-center bg-[url('/assets/quests/interior7.png')] h-screen bg-cover bg-center bg-no-repeat">
    
    <div class="absolute top-4 left-4">
        <%= link_to game_master_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>
        <% end %>
    </div>

    <div class="flex items-center justify-center h-screen">
        <div class="absolute top-4 left-4">
        <%= link_to game_master_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>
        <% end %>
    </div>

        <img src="/assets/quests/parchment.png" class="mt-[2em] w-[62em] rotate-90"/>
        <div class="absolute">
            <p class="text-2xl text-black font-bold mb-2">QUETS AVALAIBLE</p>
            <table class="mb-[5em] text-black min-w-full">
                <thead class="font-semibold">
                    <th scope="col" class="px-2 py-2">Name</th>
                    <th scope="col" class="px-2 py-2">Exp</th>
                    <th scope="col" class="px-2 py-2">Description</th>
                    <th scope="col" class="px-2 py-2">Action</th>
                </thead>
                <% @quests.each do |quest| %>
                <tbody class="font-medium border border-[#363062]">
                    <td class="whitespace-nowrap px-2 py-2 w-[10em]"><%= quest.name %></td>
                    <td class="whitespace-nowrap px-2 py-2 w-[10em]"><%= quest.exp %></td>
                    <td class="px-2 py-2 truncate max-w-[28em]"><%= quest.description %></td>
                    <td class="whitespace-nowrap px-2 py-2 w-[10em]">
                        <button>
                            <%= link_to 'Open', quest, class:'p-2 hover:text-[#508D69]' %>
                        </button>
                        <button >
                            <%= button_to 'Delete', quest_path(quest), method: :delete, data: { confirm: 'Are you sure?' }, class: 'p-2 hover:text-[#B31312]', remote: true %>
                        </button>
                    </td>
                </tbody>
                <% end %>   
            </table>
            <div class="flex justify-center mt-2">
                <button class="hover:text-[#CD5C08] text-black p-2 ps-3 pe-3">
                    <%= link_to 'new Quest', new_quest_path %>
                </button>
            </div>
        </div>    
    </div>  
</div>

app/views/quests/new.html.erb
<div class="overflow-hidden text-white text-center bg-[url('/assets/quests/mountains6.png')] h-screen bg-cover bg-center bg-no-repeat">
    
    <div class="absolute top-4 left-4">
        <%= link_to quests_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>
        <% end %>
    </div>
    
    <div class="flex items-center justify-center h-screen">
        <img src="/assets/quests/parchment.png" class="w-[40em]"/>
        <p class="absolute top-[130px] text-2xl text-black font-bold">New Quest</p>

        <div class="absolute top-[20px]">
            <%= render 'form' %>
        </div>
        <button class="relative bottom-60 hover:text-[#CD5C08] text-black">
            <%= link_to 'Back', quests_path %>
        </button>
    </div>
</div>

app/views/quests/show.html.erb
<div class="overflow-hidden text-white text-center bg-[url('/assets/quests/mountains5.png')] h-screen bg-cover bg-center bg-no-repeat">
    <div class="flex items-center justify-center h-screen">
        <img src="/assets/quests/parchment.png" class="w-[40em]"/>
        <div class="absolute grid grid-rows-1 gap-8 place-content-center text-black">
            <div class="mb-2">
                <p id="questTitle" class="text-2xl text-[#5CD2E6] font-bold"><%= @quest.name %></p>
            </div>
            <div class="mb-2">
                <p class="text-xl text-[#213555] font-bold">Exp: <%= @quest.exp %></p>
            </div>
            <div class="mb-2 w-[20em] max-h-[8em]">
                <p class="text-xl text-[#5C476F] font-bold break-normal"><%= @quest.description %></p>
            </div>
            <div class="mb-2 w-[20em] p-2">
                <p id="questTitle" class="text-xl font-bold">Rewards</p>
                <div class="mt-4 grid grid-cols-1 gap-2">
                    <button class="text-[#7386D5]" id="reward1"><%= @quest.item_1.name %></button>
                    <button class="text-[#7386D5]" id="reward2"><%= @quest.item_2.name %></button>
                    <button class="text-[#7386D5]" id="reward3"><%= @quest.item_3.name %></button>
                </div>
            </div>
            <div class="flex justify-center mt-2">
                <button class="hover:text-[#CD5C08] text-black p-2 ps-3 pe-3">
                    <%= link_to 'Back', quests_path %>
                </button>
            </div>
            <% [@quest.item_1, @quest.item_2, @quest.item_3].each_with_index do |item, index| %>
                <div id="popup-overlay-reward<%= index + 1 %>">
                    <div id="popup<%= index + 1 %>">
                        <div class="grid grid-rows-1 gap-4 text-center">
                        <div class="flex justify-center items-center"> 
                            <img src="/assets/PNG_inventaire/<%= item.path %>.png" alt="item">
                        </div> 
                            <p class="text-[#FFC436]"> <%= item.name %></p>
                            <% case item.categorie %>
                            <% when "weapon" %>
                                <p class="text-[#FF5151]">Attack: <%= item.stats %></p>
                            <% when "knowledge" %>
                                <p class="text-[#FF5151]">Knowledge: <%= item.stats %></p>
                            <% when "currency", "navigationalTool", "artifact", "mysticalTool", "container", "gemstone", "tool", "resource" %>
                                <p class="text-[#FF5151]">Value: <%= item.stats %></p>
                            <% when "potion" %>
                                <p class="text-[#FF5151]">Effect: <%= item.stats %></p>
                            <% else %>
                                <p class="text-[#FF5151]">Stats: <%= item.stats %></p>
                            <% end %>
                            <p class="w-[20em] text-[#EEEDED]"> <%= item.description %> </p>
                        </div>
                        <div class="text-[#C51605]" id="popup-close<%= index + 1 %>">X</div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>