config/routes.rb
Rails.application.routes.draw do
  get 'aquariu/show'
  get 'tauru/show'
  get 'scorpio/show'
  get 'arie/show'
  get 'gemini/show'
  get 'sagittariu/show'
  get 'characters/new'
  get 'characters/create'

  # INVENTORY
  get "/inventory", to: "inventory#index"
  put "/inventory", to: "inventory#update"

  resource :session
  resource :registration
  resource :password_reset
  resource :password
  resources :quests
  resources :items , only: [:index, :show, :new, :edit, :create, :update, :destroy] 
  resources :questions
  resources :npcs

  resource :game_master
  resources :rewards, only: [:index, :show]
  
  resources :characters
  resources :parties

  get '/game_map/:id', to: 'game_map#show', as: 'game_map'
  resources :arie
  resources :gemini
  resources :sagittariu
  resources :scorpio
  resources :tauru
  resources :aquariu

  
  # Defines the root path route ("/")
  root "main#index"
end

app/models/archer.rb
class Archer < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  # belongs_to :classe
  belongs_to :user

end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
    has_many :character
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/enigma.rb
class Enigma < ApplicationRecord
    validates :question, presence: true
    validates :correct_response, presence: true, inclusion: { in: %w(response1 response2 response3) }
    validates :response1, presence: true
    validates :response2, presence: true
    validates :response3, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates :path, presence: true
    validates :name, presence: true
    validates :categorie, presence: true
    validates :description, presence: true
    validates :stats, presence: true
end

app/models/mage.rb
class Mage < ApplicationRecord
end

app/models/npc.rb
class Npc < ApplicationRecord
    attr_accessor :avatar
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
end

app/models/quest.rb
class Quest < ApplicationRecord
    belongs_to :item_1, class_name: 'Item', foreign_key: 'item_1_id'
    belongs_to :item_2, class_name: 'Item', foreign_key: 'item_2_id'
    belongs_to :item_3, class_name: 'Item', foreign_key: 'item_3_id'
  end
  

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
    normalizes :email, with: ->(email) {email.strip.downcase}

    has_many :characters
    has_many :parties
end

app/models/warrior.rb
class Warrior < ApplicationRecord
end

app/controllers/game_masters_controller.rb
class GameMastersController < ApplicationController
    def index
    end

    def show
    end
end

app/helpers/arie_helper.rb
module ArieHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/game_master_helper.rb
module GameMasterHelper
end

app/helpers/game_masters_helper.rb
module GameMastersHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/tauru_helper.rb
module TauruHelper
end

app/views/game_masters/show.html.erb
<div class="overflow-hidden text-white text-center bg-[url('/assets/gameMaster/tunnel8.png')] h-screen bg-cover bg-center bg-no-repeat">
    <div class="text-left pt-4">
        <%= link_to root_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>        
        <% end %>
    </div>
   
    <div class="flex items-center justify-center">
        <div class="grid grid-rows-1 grid-flow-col gap-4">
            <div class="flex items-center justify-center">
                <img src="/assets/gameMaster/papyrus.png" class="w-[14em] h-[22em]"/>
                <div class="absolute">
                    <p class="text-3xl text-black font-bold mb-2">
                    <%= link_to "QUESTS", quests_path, class: "hover:text-[#E92306]" %>
                    </p>
                </div>
            </div>
            <div class="flex items-center justify-center">
                <img src="/assets/gameMaster/papyrus.png" class="w-[14em] h-[22em]"/>
                <div class="absolute">
                    <p class="text-2xl text-black font-bold mb-2">
                    <%= link_to "ENIGMAS", questions_path %>
                    </p>
                </div>
            </div>
            <div class="flex items-center justify-center">
                <img src="/assets/gameMaster/papyrus.png" class="w-[14em] h-[22em]"/>
                <div class="absolute">
                    <p class="text-2xl text-black font-bold mb-2">
                        <%= link_to "ITEMS", items_path, class: "hover:text-[#E92306]" %>
                    </p>
                </div>
            </div>
            <div class="flex items-center justify-center">
                <img src="/assets/gameMaster/papyrus.png" class="w-[14em] h-[22em]"/>
                <div class="absolute">
                    <p class="text-2xl text-black font-bold mb-2">
                        <%= link_to "NPC", new_npc_path, class: "hover:text-[#E92306]" %>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>