config/routes.rb
Rails.application.routes.draw do
  get 'aquariu/show'
  get 'tauru/show'
  get 'scorpio/show'
  get 'arie/show'
  get 'gemini/show'
  get 'sagittariu/show'
  get 'characters/new'
  get 'characters/create'

  # INVENTORY
  get "/inventory", to: "inventory#index"
  put "/inventory", to: "inventory#update"

  resource :session
  resource :registration
  resource :password_reset
  resource :password
  resources :quests
  resources :items , only: [:index, :show, :new, :edit, :create, :update, :destroy] 
  resources :questions
  resources :npcs

  resource :game_master
  resources :rewards, only: [:index, :show]
  
  resources :characters
  resources :parties

  get '/game_map/:id', to: 'game_map#show', as: 'game_map'
  resources :arie
  resources :gemini
  resources :sagittariu
  resources :scorpio
  resources :tauru
  resources :aquariu

  
  # Defines the root path route ("/")
  root "main#index"
end

app/models/archer.rb
class Archer < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  # belongs_to :classe
  belongs_to :user

end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
    has_many :character
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/enigma.rb
class Enigma < ApplicationRecord
    validates :question, presence: true
    validates :correct_response, presence: true, inclusion: { in: %w(response1 response2 response3) }
    validates :response1, presence: true
    validates :response2, presence: true
    validates :response3, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    validates :path, presence: true
    validates :name, presence: true
    validates :categorie, presence: true
    validates :description, presence: true
    validates :stats, presence: true
end

app/models/mage.rb
class Mage < ApplicationRecord
end

app/models/npc.rb
class Npc < ApplicationRecord
    attr_accessor :avatar
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
end

app/models/quest.rb
class Quest < ApplicationRecord
    belongs_to :item_1, class_name: 'Item', foreign_key: 'item_1_id'
    belongs_to :item_2, class_name: 'Item', foreign_key: 'item_2_id'
    belongs_to :item_3, class_name: 'Item', foreign_key: 'item_3_id'
  end
  

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
    normalizes :email, with: ->(email) {email.strip.downcase}

    has_many :characters
    has_many :parties
end

app/models/warrior.rb
class Warrior < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController 
    
    def index
        @items = Item.all().order(name: :asc)
    end 

    # VIEW POUR LA CREATION D'ITEM , [SUBMITION] => METHOD "create"  
    def new
        @item = Item.new
    end

    # RECUPERER LES CHAMPS ET METTRE DANS LA TABLE "item" , [REDIRECT] => PAGE "/items"  
    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to(items_path())
        else
            render :new
        end            
    end

    # VIEW POUR LA MODIF D'ITEM , [SUBMITION] => METHOD "update"
    def edit
        @item = Item.find(params[:id])
    end
    
    # MET A JOUR LES ITEM DANS LA TABLE "item" ,  [REDIRECT] => PAGE "/items"  
    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)   
            redirect_to(items_path())
        else   
            render :new
        end
    end

    # SUPPRESSION D'ITEM PAR "id" DANS LA TABLE "item" 
    def destroy
        item = Item.find(params[:id])
        item.destroy

        inventory = Inventory.where(id_item: params[:id])
        if inventory.length > 0 
            inventory.destroy_all
        end
        
        redirect_to(items_path())
    end

    private

    # DEFINIER LES CHAMPS A UTILISER LORS DE LA MISE EN DB  
    def item_params
        params.require(:item).permit(:path, :name, :categorie, :stats, :description)
    end

end

app/helpers/arie_helper.rb
module ArieHelper
end

app/helpers/enigma_helper.rb
module EnigmaHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/tauru_helper.rb
module TauruHelper
end

app/views/items/edit.html.erb
<%= link_to items_path do %>
    <i class="fas fa-arrow-left relative left-[5%] top-4 text-[40px] hover:scale-125"></i>
<% end %>
<div class="flex justify-center">
    <div class="mt-6" >
       <%= form_with model: @item, local: true do |form| %>
       <h1 class="text-2xl text-center mb-4"> Item</h1>
            <div class='mb-4 flex flex-col items-center' >
                <%= form.label(:path, class: "")%>
                <%= form.text_field(:path, class: "border text-center") %>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= form.label(:name, class: "") %>
                <%= form.text_field(:name, class: "border text-center") %>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= form.label :categorie %>
                <%= form.select(:categorie, ['none', 'weapon', 'shield', 'armor'], {}, {class: "border w-full py-2 text-center"})%>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= form.label :stats %>
                <%= form.number_field :stats, class: "border w-2/4 text-center" %>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= form.label :description %>
                <%= form.text_area :description, class: "border p-2" %>
            </div>
            <div class='mb-4'>
                <img src="/assets/PNG_inventaire/<%= @item.path %>.png" alt="item" class="ml-auto mr-auto border p-4" />
            </div>
            <div class='mb-4 flex justify-center'>
                <%= form.submit("Edit item", class: "bg-cyan-400 p-2 rounded-[7%] cursor-pointer hover:bg-cyan-300") %>
            </div>
       <% end %>
    </div>
</div>

app/views/items/index.html.erb
<div>
    <img src="/assets/home/castle_proto_3.png" class="absolute w-full h-full object-cover">
</div>

    <%# Return button %>
    <div class="absolute z-50 top-4 left-4 custom_link">
        <%= link_to game_master_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>
        <% end %>
    </div>

    <%# Title %>
    <div class="relative text-center text-white text-2xl my-4">
        <h1 class="">List of item</h1>
    </div>

    <%# Button add item %>
    <div class="relative text-white left-[115px]">
        <%= link_to new_item_path() do %>
            <img src="/assets/home/buttons/menu_button_01.png" class="custom_link">
            <button class="absolute top-[15px] left-[38px] rounded-[7%] text-[13px] bold custom_link">Add new item</button>
        <% end %>
    </div>

    <%# Table %>
    <div class="relative m-auto flex justify-center align-center items-center w-[80vw] text-white">
        <table class="bg-black/50 w-[100%] mt-4">
            <thead>
                <tr>
                    <th class="h-[8vh]">id</th>
                    <%# <th>path</th> %>
                    <th>name</th>
                    <th>categorie</th>
                    <th>status</th>
                    <th>picture</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @items.each do |item| %>
                    <tr class="hover:bg-sky-700">
                        <td class="text-center py-2">
                            <%= item.id %>
                        </td>
                        <%# <td class="text-center"> %>
                            <%# <%= item.path %>
                        <%# </td> %>
                        <td class="text-center">
                            <%= item.name %>
                        </td>
                        <td class="text-center">
                            <%= item.categorie %>
                        </td>
                        <td class="text-center">
                            <%= item.stats %>
                        </td>
                        <td class="flex justify-center items-center">
                            <img src="/assets/PNG_inventaire/<%= item.path %>.png" alt="item">
                        </td>
                        <td class="text-center">
                            <%= link_to edit_item_path(item) do %>
                                <button class="bg-sky-700 px-2 py-1 text-white rounded-[10%] hover:bg-sky-600">Edit</button>
                            <% end %>
                        </td>
                        <td class="text-center">
                            <button class="bg-rose-600 px-2 py-1 text-white rounded-[10%] hover:bg-rose-500 ">
                                <%= link_to "Delete", item_path(item), data: {confirm: "Really?", turbo_method: :delete} %>
                            </button>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>
    </div>

app/views/items/new.html.erb
<div class="flex justify-center align-center items-center h-full" style="background: url('/assets/home/dark_forest_01.png') no-repeat center center fixed; background-size: cover;"> 
    <div class="absolute top-4 left-4">
        <%= link_to items_path do %>
            <%= image_tag("/assets/home/close_button.png", class: "w-12") %>
        <% end %>
    </div>
<div class="">
    <div class="mt-10" >
       <%= form_with model: @item, local: true do |f| %>
       <h1 class="text-2xl text-center mb-4">Item</h1>
            <div class='mb-4 flex flex-col items-center'>
                <%= f.label(:path, class: "")%>
                <%= f.text_field(:path, class: "border") %>
            </div>
             <div class='mb-4 flex flex-col items-center'>
                <%= f.label(:name, class: "") %>
                <%= f.text_field(:name, class: "border") %>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= f.label :categorie %>
                <%= f.select(:categorie, ['none', 'weapon', 'shield', 'armor'], {}, {class: "w-full py-2 text-center border"})%>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= f.label :stats %>
                <%= f.number_field :stats, class: "border text-center w-[50%]", min: 0 %>
            </div>
            <div class='mb-4 flex flex-col items-center'>
                <%= f.label :description %>
                <%= f.text_area :description, class: "border text-center" %>
            </div>
            <div class='relative mb-4 flex justify-center'>
                <img src="/assets/home/button_home3.png" class="w-[200px]">
                <%= form.submit("Create item", class: "absolute top-[44px] p-2 text-white hover:text-[#E92306] custom_link") %>
                </div>
            <% end %>
        </div>
    </div>
</div>